/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include <string.h>
#include <stdio.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define WIN_SETTINGS		(GUI_ID_USER + 0x10)

#define BTN_CANCEL        	(GUI_ID_USER + 0x11)
#define BTN_OK        		(GUI_ID_USER + 0x12)

#define	TXT_RESOLUTION		(GUI_ID_USER + 0x13)
#define	TXT_FORMAT			(GUI_ID_USER + 0x14)
#define	TXT_EFFECT			(GUI_ID_USER + 0x15)
#define	TXT_SCALE			(GUI_ID_USER + 0x16)
#define	TXT_EXPOSURE		(GUI_ID_USER + 0x17)
#define	TXT_GAIN			(GUI_ID_USER + 0x18)
#define	TXT_BRIGHTNESS		(GUI_ID_USER + 0x19)
#define	TXT_CONTRAST		(GUI_ID_USER + 0x1A)
#define	TXT_SATURATION		(GUI_ID_USER + 0x1B)
#define	TXT_GAIN_CEIL		(GUI_ID_USER + 0x1C)
#define	TXT_RCH_GAIN		(GUI_ID_USER + 0x1D)
#define	TXT_GCH_GAIN		(GUI_ID_USER + 0x1E)
#define	TXT_BCH_GAIN		(GUI_ID_USER + 0x1F)

#define DDWN_RESOLUTION		(GUI_ID_USER + 0x20)
#define DDWN_FORMAT			(GUI_ID_USER + 0x21)
#define DDWN_EFFECT			(GUI_ID_USER + 0x22)

#define SBOX_SCALE        	(GUI_ID_USER + 0x23)

#define SLDR_EXPOSURE		(GUI_ID_USER + 0x24)
#define SLDR_GAIN        	(GUI_ID_USER + 0x25)
#define SLDR_BRIGHTNESS		(GUI_ID_USER + 0x26)
#define SLDR_CONTRAST		(GUI_ID_USER + 0x27)
#define SLDR_SATURATION		(GUI_ID_USER + 0x28)
#define SLDR_GAIN_CEIL		(GUI_ID_USER + 0x29)
#define SLDR_RCH_GAIN		(GUI_ID_USER + 0x2A)
#define SLDR_GCH_GAIN		(GUI_ID_USER + 0x2B)
#define SLDR_BCH_GAIN		(GUI_ID_USER + 0x2C)

#define CBOX_EXPOSURE		(GUI_ID_USER + 0x2D)
#define CBOX_GAIN			(GUI_ID_USER + 0x2E)
#define CBOX_AWB			(GUI_ID_USER + 0x2F)
#define CBOX_HFLIP			(GUI_ID_USER + 0x30)
#define CBOX_VFLIP			(GUI_ID_USER + 0x31)
#define CBOX_CBAR			(GUI_ID_USER + 0x32)
#define CBOX_NIGHT_MODE		(GUI_ID_USER + 0x33)
#define CBOX_HIST_AEC		(GUI_ID_USER + 0x34)
#define CBOX_DENOISE		(GUI_ID_USER + 0x35)

#define	LBL_EXPOSURE		(GUI_ID_USER + 0x36)
#define	LBL_GAIN			(GUI_ID_USER + 0x37)
#define	LBL_CONTRAST		(GUI_ID_USER + 0x38)
#define	LBL_BRIGHTNESS		(GUI_ID_USER + 0x39)
#define	LBL_SATURATION		(GUI_ID_USER + 0x3A)
#define	LBL_GAIN_CEIL		(GUI_ID_USER + 0x3B)
#define	LBL_RCH_GAIN		(GUI_ID_USER + 0x3C)
#define	LBL_GCH_GAIN		(GUI_ID_USER + 0x3D)
#define	LBL_BCH_GAIN		(GUI_ID_USER + 0x3E)

// USER START (Optionally insert additional defines)
WM_HWIN CreateSettings(void);
// USER END

